### PR TITLE
Version 1.3

### PR DESCRIPTION
**Pull request by PanoramicPanda**
- Add support for various Crit styles
- Update roll button iconography

### CODE REVIEW

**Review by JasonCostanza — CHANGES_REQUESTED** [review]
It has some errors on `Save` and `Reset`. I'll debug them this afternoon and try to fix if you don't have time to look at it.

**Comment by PanoramicPanda** [comment]
Fix should be in now, but I can't verify until way later today. As soon as you mentioned the problem, I knew what it was.

**Comment by JasonCostanza** [comment]
Those are good to go. New issue I didn't check before, loading is broken
image

Like you, will debug later so whoever gets there first wins the imaginary cake 😆

**Review by JasonCostanza — APPROVED** [review]
After my commit, everything looks gold. Send it!

I'll draft the release when you complete the merge

**Comment by PanoramicPanda** [comment]
This is the release merge :P Has changes in readme and manifest, so merge it and release it when you're comfortable.

**Pull request merged**
