### PR TITLE
Feature/number box

### LINKED ISSUE #20: Feature Request: Modifier be a number box?
**Is your feature request related to a problem? Please describe.**
I have a roll that has +17 modifier on it. Having to click 17 times feels bad.

**Describe the solution you'd like**
Modifier be a number box instead. Maybe with a +/- clickable above/below?

### PR DESCRIPTION
**Pull request by PanoramicPanda**
Resolves #20

### CODE REVIEW

**Comment by PanoramicPanda** [comment]
Found a bug, fixing.

**Comment by JasonCostanza** [comment]
What can we do to possibly improve the visuals of this? it's kind of feeling "dark on dark on dark" without much visual aid. In the empty picture the cursor is actually active but it's a black cursor so invisible.
image
image

Functionally works well

**Comment by JasonCostanza** [comment]
Maybe we drop the circle icon and replace it with something else, then make the text box either outlined or some lighter color so it's more well defined visually what the player is needing to do

**Comment by PanoramicPanda** [comment]
Ah, forgot to fix that on hover. It's already not showing that black box once you're using it.

**Comment by PanoramicPanda** [comment]
Update with main, let me know if you think that's enough or it's back to the drawing board.

**Review by JasonCostanza — APPROVED** [review]
Tested locally, looks good!

**Pull request merged**
